ctocommunication_start:
    path:     /ctoCommunication
    defaults:
        _controller: MenAtWork\CtoCommunicationBundle\Controller\Client:execute
        _scope: frontend
        _token_check: false

